name: Security

on: [push, pull_request, schedule]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: .devcontainer/conflux/utils

    - name: Run npm audit
      run: npm audit --audit-level=high
      working-directory: .devcontainer/conflux/utils