name: Devkit Server Docker Image

on:
  push:
    branches:
      - main  # Run the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/conflux
          target: openvscode
          push: true
          tags: spcfxda/conflux-devkit-server:latest

      - name: Log out from Docker Hub
        run: docker logout